### ISSUE TITLE
Final STL file empty and strange output

### ISSUE THREAD

**Issue by amoeba** [dougmccune/shp2stl#1]
I heard about this node package from your excellent [blog post](http://dougmccune.com/blog/2014/12/30/using-shp2stl-to-convert-maps-to-3d-models/). I haven't, however, been able to replicate your approach with  my own shapefile. My code and shapefile is over at:

https://github.com/amoeba/3dmaps

The output I get it this:

```
$ node convert.js
bounds: Infinity Infinity -Infinity -Infinity (spherical)
pre-quantization: 111.195km (1.00°) 111.195km (1.00°)
topology: 0 arcs, 0 points
topojson done
simplification: effective minimum area 0.00
simplification: retained 0 / 0 points (NaN%)
making top planes
making side planes
making bottom planes
done making 3D planes
```

And the resulting STL file only contains:

```
solid
endsolid
```

Is it because of my strange projection? Something else? I've poked around your source to the best of my ability but I can't seem to figure out where I'm messing up.

**Comment by dougmccune** [comment]
Looks like your shapefile is line data, not polygon data. Sadly shp2stl will only work with proper poly data. It filters your features to only include polygons, which in this case filters out all the shapes. You can try to convert the lines to polys somehow. QGIS has some tools to do so, although I didn't have much initial luck trying that on your data.

**Comment by amoeba** [comment]
Thanks for putting in time to try converting for me. Your explanation makes sense.

Thanks!
